apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: decode
  labels:
    llm-d.ai/role: decode
spec:
  selector:
    matchLabels:
      llm-d.ai/role: decode
  podMetricsEndpoints:
    - port: "modelserver"
      path: /metrics
      interval: 30s
