# Deprecated in llm-d. Retained only to support migration to
# agentgateway and will be removed in a future release.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kgateway
  - gateway-parameters.yaml

patches:
  - target:
      kind: Gateway
    patch: |
      - op: add
        path: /spec/infrastructure
        value:
          parametersRef:
            name: agentgateway-params
            group: agentgateway.dev
            kind: AgentgatewayParameters
